### ISSUE TITLE
i want to know what does this use for?

### ISSUE THREAD

**Issue by wonderfuer** [madskristensen/BrowserSync#5]

**Comment by madskristensen** [comment]
It's explained here https://github.com/madskristensen/BrowserSync/blob/master/README.md

**Comment by wonderfuer** [comment]
thanks

**Comment by Bartolomeus-649** [comment]
Yeah, the ReadMe say what it does, but...
1. Which problem is this extension a solution to?
2. Why would I want to have several browsers running?

Perhaps it's an example of how to use "Browser Link", intended more for educational purposes?
